
package ventana;

// Importaciones.

import proyectoamazon.GlobalVariables;
import proyectoamazon.NodeProduct;
import proyectoamazon.Functions;
import proyectoamazon.ListWarehouse;
import proyectoamazon.Product;
import proyectoamazon.NodeWarehouse;

/**
 *
 * @author victorpointud
 */
public class AddProductWindow extends javax.swing.JFrame {

    /**
     * Creates new form AddProductWindow
     */
    
    // Inicio.
    
    
    public AddProductWindow() {
    
    // Añadir Ventana De Producto.
    
        initComponents();
        Functions fc = new Functions();
        this.setLocationRelativeTo(null);
        AddWarehouses(GlobalVariables.getListWarehouse());
    
    // Retorna Las Variables De La Lista Warehouse.
    }
    
    
    public void AddWarehouses (ListWarehouse listWarehouse) {
    
    // Añadir Almacenes.
    
        NodeWarehouse pointer = listWarehouse.getHead();
        int index = 0;
        while (pointer != null) {
            String warehouseLetter = pointer.getElement().getName();
            PickWarehouse.insertItemAt(warehouseLetter, index);
            index++;
            pointer = pointer.getNext();
        }
    // Retorna el Alamacen Como Nodo.
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TitleWarehouse = new javax.swing.JLabel();
        PickWarehouse = new javax.swing.JComboBox<>();
        ProductTitle = new javax.swing.JLabel();
        NameProduct = new javax.swing.JTextField();
        QuantityTitle = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleWarehouse.setBackground(new java.awt.Color(78, 80, 82));
        TitleWarehouse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TitleWarehouse.setForeground(new java.awt.Color(255, 255, 255));
        TitleWarehouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleWarehouse.setText("Nombre del almacen");
        TitleWarehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TitleWarehouse.setOpaque(true);
        jPanel1.add(TitleWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 30));

        PickWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickWarehouseActionPerformed(evt);
            }
        });
        jPanel1.add(PickWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 120, 30));

        ProductTitle.setBackground(new java.awt.Color(78, 80, 82));
        ProductTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProductTitle.setForeground(new java.awt.Color(255, 255, 255));
        ProductTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProductTitle.setText("Nombre del producto");
        ProductTitle.setOpaque(true);
        jPanel1.add(ProductTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 30));

        NameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameProductActionPerformed(evt);
            }
        });
        jPanel1.add(NameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 120, 30));

        QuantityTitle.setBackground(new java.awt.Color(78, 80, 82));
        QuantityTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QuantityTitle.setForeground(new java.awt.Color(255, 255, 255));
        QuantityTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QuantityTitle.setText("Cantidad");
        QuantityTitle.setOpaque(true);
        jPanel1.add(QuantityTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 70, 30));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 70, 30));

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Gestión");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acastro_STK103__01.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    // Acción Del Botón 1 (Añadir).
    
        String newproductname = NameProduct.getText();
        int newproductqty = (Integer) jSpinner1.getValue();
        String warehouseLetter = String.valueOf(PickWarehouse.getSelectedItem());
        
        ListWarehouse list = GlobalVariables.getListWarehouse();
        NodeWarehouse pointer = list.getHead();
        boolean keepGoing = true;
        while (pointer != null && keepGoing) {
            if (warehouseLetter.equals(pointer.getElement().getName())) {
                keepGoing = false;
                Product newproduct = new Product(newproductname, newproductqty);
                NodeProduct newnodeproduct = new NodeProduct(newproduct);
                pointer.getElement().getListOfProducts().AddProduct(newnodeproduct);
            }
            pointer = pointer.getNext();
        }
    
    // Retorna El Elemento Añadido A La Lista De Productos.
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PickWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickWarehouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickWarehouseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    // Acción Del Botón 2 (Gestión).
    
        ManagementWindow mw = new ManagementWindow();
        this.setVisible(false);
        mw.setVisible(true);
    
    // Retorna Ventana Siguiente.
    
    }//GEN-LAST:event_jButton2ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NameProduct;
    private javax.swing.JComboBox<String> PickWarehouse;
    private javax.swing.JLabel ProductTitle;
    private javax.swing.JLabel QuantityTitle;
    private javax.swing.JLabel TitleWarehouse;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
