
package ventana;

// Importaciones.

import proyectoamazon.Warehouse;
import proyectoamazon.GlobalVariables;
import proyectoamazon.NodeWarehouse;
import javax.swing.JOptionPane;

/**
 *
 * @author victorpointud
 */
public class AddWarehouse extends javax.swing.JFrame {
    
    // Inicio.
    
    String newwarehousename;
    String[] almacenes = AllWarehouses(GlobalVariables.getListWarehouse());
    /**
     * Creates new form AddWarehouse
     */
    public AddWarehouse() {
        initComponents();
        this.setLocationRelativeTo(null);
        
          
    }
    
    public String[] AllWarehouses(ListWarehouse listWarehouse) {
        
    // Todos Los Almacenes.
    
        String[] almacenes = new String[listWarehouse.getLength()];
        NodeWarehouse pointer = listWarehouse.getHead();
        int index = 0;
        while (pointer != null) {
            String warehouseLetter = pointer.getElement().getName();
            almacenes[index] = warehouseLetter;
            index++;
            pointer = pointer.getNext();
        }
        return almacenes;
    
    // Retorna Almacenes.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreAlmacen = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CaracteristicasAlmacen = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAlmacenActionPerformed(evt);
            }
        });
        getContentPane().add(NombreAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 60, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Agregar Almacen");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ingrese el nombre del Almacen que desea agregar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        CaracteristicasAlmacen.setText("Continuar");
        CaracteristicasAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaracteristicasAlmacenActionPerformed(evt);
            }
        });
        getContentPane().add(CaracteristicasAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 90, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pulse el boton para continuar con la creación del Almacen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addwarehouse.jpg")));
        jLabel5.setText("Letra del Abecedario en Mayuscula");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 290));

        Menu.setText("Gestión");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaracteristicasAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaracteristicasAlmacenActionPerformed
        
    // Mostrar Caracteristicas Del Almacen A Crear.
    
        boolean nombreexiste = false;
        for (int i = 0; i < almacenes.length; i++) {
            if (NombreAlmacen.getText().equals(almacenes[i])) {
                nombreexiste = true;
                break;
            }            
        } 
        if (NombreAlmacen.getText().length() < 2 && NombreAlmacen.getText().matches("^[a-zA-Z]*$")) {
            if (NombreAlmacen.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Error, no agrego nada");
                this.setVisible(false);
            }
            else if (!nombreexiste) {
                    WarehouseCharacteristics wc = new WarehouseCharacteristics();
                    newwarehousename = NombreAlmacen.getText();
                    this.setVisible(false);
                    this.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
                    wc.setVisible(true);
                    ListProducts listpro = new ListProducts(null);
                    Warehouse newWarehouse = new Warehouse(newwarehousename, listpro);
                    ListWarehouse list = GlobalVariables.getListWarehouse();
                    list.insertEnd(newWarehouse);
                    list.printList();
                    System.out.println(list.getLast().getName());
             
            }
            else{
                JOptionPane.showMessageDialog(null, "Error, el almacen ya existe");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error, ingrese una letra del abecedario");
        }
    
    // Retorna Error Si Ya Existe Un Almacen Parecido y/o Lo Guarda.
    
    }//GEN-LAST:event_CaracteristicasAlmacenActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
    
    // Acción Del Botón (Menú).
    
        ManagementWindow mw = new ManagementWindow();
        this.setVisible(false);
        mw.setVisible(true);
    
    // Retorna Nueva Ventana.
    }//GEN-LAST:event_MenuActionPerformed

    private void NombreAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAlmacenActionPerformed
        newwarehousename = NombreAlmacen.getText();
    }//GEN-LAST:event_NombreAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        String info[] = new String[2];
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWarehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddWarehouse().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaracteristicasAlmacen;
    private javax.swing.JButton Menu;
    private javax.swing.JTextField NombreAlmacen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
