
package ventana;

import proyecto1.Functions;

// Importaciones.

import proyecto1.GlobalVariables;

/**
 *
 * @author victorpointud
 */
public class ManagementWindow extends javax.swing.JFrame {

    /**
     * Creates new form ManagementWindow
     */
    public ManagementWindow() {
        
    // Inicio.
    
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ShowGraphsButton = new javax.swing.JButton();
        AddProductButton = new javax.swing.JButton();
        Almacen = new javax.swing.JButton();
        AddTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShowGraphsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ShowGraphsButton.setText("Mostrar grafo");
        ShowGraphsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowGraphsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ShowGraphsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 50));

        AddProductButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddProductButton.setText("Producto");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 110, 50));

        Almacen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Almacen.setText("Almacen");
        Almacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlmacenActionPerformed(evt);
            }
        });
        jPanel1.add(Almacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, 50));

        AddTitle.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AddTitle.setText("Agregar:");
        jPanel1.add(AddTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Gestion De Almacen");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 160, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/management.jpg")));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowGraphsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowGraphsButtonActionPerformed
        
    // Acción Botón (Gráficos).
        
        GraphWindow gw = new GraphWindow();
        gw.setVisible(true);
        
    // Retorna Ventana Gráfico.
    }//GEN-LAST:event_ShowGraphsButtonActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        
    // Acción Botón (Añadir Producto).
    
        AddProductWindow pw = new AddProductWindow();
        this.setVisible(false);
        pw.setVisible(true);
        
    // Retorna Producto Añadido En Siguiente Ventana.
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void AlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlmacenActionPerformed
        
    // Acción Botón (Almacen).
        
        AddWarehouse aw = new AddWarehouse();
        
        this.setVisible(true);
        aw.setVisible(true);
        
    // Retorna Añadir Almacen.
    }//GEN-LAST:event_AlmacenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    // Acción Botón 1 (Menú).
    
        MenuWindow mw = new MenuWindow();
        
        this.setVisible(false);
        mw.setVisible(true);
        
    // Retorna Ventana de Menú.
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductButton;
    private javax.swing.JLabel AddTitle;
    private javax.swing.JButton Almacen;
    private javax.swing.JButton ShowGraphsButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
