
package ventana;

// Importaciones.

import proyecto1.AdjacencyMatrix;
import proyecto1.Functions;
import proyectoamazon.GlobalVariables;
import proyectoamazon.NodeWarehouse;
import proyecto1.SimpleListWithArray;
import proyecto1.ListWarehouse;

/**
 *
 * @author victorpointud
 */
public class ReportsWindows extends javax.swing.JFrame {

    /**
     * Creates new form ReportsWindows
     */
    public ReportsWindows() {
        
    // Inicio.
    
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DFS = new javax.swing.JButton();
        BFS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Reporte = new javax.swing.JTextArea();
        Menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DFS.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        DFS.setText("DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });
        jPanel1.add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 160, 70));

        BFS.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        BFS.setText("BFS");
        BFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFSActionPerformed(evt);
            }
        });
        jPanel1.add(BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 160, 70));

        Reporte.setColumns(20);
        Reporte.setRows(5);
        jScrollPane1.setViewportView(Reporte);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 470, 150));

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/report.jpg")));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        
    // Acción Botón (DFS).
    
        ListWarehouse list = GlobalVariables.getListWarehouse();
        
        AdjacencyMatrix graph = new AdjacencyMatrix(list.getLength());
        graph.createMatrix(list);
        

        NodeWarehouse pointer5 = list.getHead();
        SimpleListWithArray list1 = new SimpleListWithArray(list.getLength());
//        
        while (pointer5 != null){
            graph.addVertax(pointer5.getElement().getName());
            list1.addAtTheEnd(pointer5.getElement().getName());
            pointer5 = pointer5.getNext();
        }
       
        GlobalVariables.setDfs(graph.listProductsDFS(graph, list1, list));
        
        Reporte.setText(GlobalVariables.getDfs());
        
    // Retorna Acción de DFS.
    }//GEN-LAST:event_DFSActionPerformed

    private void BFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFSActionPerformed
        
    // Acción Botón (BFS).
    
        ListWarehouse list = GlobalVariables.getListWarehouse();
        
        AdjacencyMatrix graph = new AdjacencyMatrix(list.getLength());
        graph.createMatrix(list);
        

        NodeWarehouse pointer5 = list.getHead();
        SimpleListWithArray list1 = new SimpleListWithArray(list.getLength()); 
        while (pointer5 != null){
            graph.addVertax(pointer5.getElement().getName());
            list1.addAtTheEnd(pointer5.getElement().getName());
            pointer5 = pointer5.getNext();
        }
        
        GlobalVariables.setBfs(graph.listProductsBFS(graph, list1, list));
        
        Reporte.setText(GlobalVariables.getBfs());
        
    // Retorna Acción BFS.
    }//GEN-LAST:event_BFSActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        
    // Acción Botón (Menú).
        
        MenuWindow mw = new MenuWindow ();
        
        
        this.setVisible(false);
        mw.setVisible(true);
        
    // Muestra Ventana Menú.
    }//GEN-LAST:event_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportsWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BFS;
    private javax.swing.JButton DFS;
    private javax.swing.JButton Menu;
    private javax.swing.JTextArea Reporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
